### ISSUE TITLE
rust-analyzer panicks on `duckdb_entrypoint_c_api` due to lack of the envvars

### ISSUE THREAD

**Issue by yutannihilation** [duckdb/extension-template-rs#15]
`#[duckdb_entrypoint_c_api()]` macro requires `DUCKDB_EXTENSION_MIN_DUCKDB_VERSION` and `DUCKDB_EXTENSION_NAME` envvars if used without arguments. When running `make debug`, these are provided form the Makefile, so the build succeeds. However, rust-analyzer doesn't know the values.

<img src="https://github.com/user-attachments/assets/67b90587-f06a-4480-8754-2d77ca4b198e" width="60%" />

Can this be solved? I think one option is to add these lines to `.cargo/config.toml`. If this looks good, I can create a pull request.

```toml
[env]
DUCKDB_EXTENSION_MIN_DUCKDB_VERSION = "v1.2.0"
DUCKDB_EXTENSION_NAME = "rusty_quack"
```
